// export const API_BASE_URL = 'http://localhost/strictlyair-web/api';
export const API_BASE_URL = 'https://www.strictlyairandcargo.com/api';
// Get Data from local storage
export const FETCH_DATA_FROM_STORAGE = "FETCH_DATA_FROM_STORAGE";
export const FETCH_DATA_FROM_STORAGE_SUCCESS = "FETCH_DATA_FROM_STORAGE_SUCCESS";
export const FETCH_DATA_FROM_STORAGE_FAIL = "FETCH_DATA_FROM_STORAGE_FAIL";

// Auth login
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PHONE_CHANGED = "PHONE_CHANGED";
export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";

export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL = "USER_DETAIL";

// Auth register
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER = "REGISTER_USER";
export const CONFIRM_PASSWORD_CHANGED = "CONFIRM_PASSWORD_CHANGED";
export const FIRST_NAME_CHANGED = "FIRST_NAME_CHANGED";
export const LAST_NAME_CHANGED = "LAST_NAME_CHANGED";
export const CITY_NAME_CHANGED = "CITY_NAME_CHANGED";
// Auth Verification
export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const SEND_VERIFICATION_CODE_SUCCESS = "SEND_VERIFICATION_CODE_SUCCESS";
export const SEND_VERIFICATION_CODE_FAIL = "SEND_VERIFICATION_CODE_FAIL";
export const VERIFICATION_CODE_CHANGED = "VERIFICATION_CODE_CHANGED";
// Resend Verification Code
export const RESEND_VERIFICATION_CODE = "RESEND_VERIFICATION_CODE";
export const RESEND_VERIFICATION_CODE_SUCCESS = "RESEND_VERIFICATION_CODE_SUCCESS";
export const RESEND_VERIFICATION_CODE_FAIL = "RESEND_VERIFICATION_CODE_FAIL";
// Auth send password reset code
export const SEND_PASSWORD_RESET_CODE_SUCCESS = "SEND_PASSWORD_RESET_CODE_SUCCESS";
export const SEND_PASSWORD_RESET_CODE_FAIL = "SEND_PASSWORD_RESET_CODE_FAIL";
export const SEND_PASSWORD_RESET_CODE = "SEND_PASSWORD_RESET_CODE";
// Auth change password
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const PASSWORD_RESET_CODE_CHANGED = "PASSWORD_RESET_CODE_CHANGED";

export const LOGIN_USER_DETAIL = "LOGIN_USER_DETAIL";

// Matchs
export const MATCH_TYPE_CHANGED = "MATCH_TYPE_CHANGED";
export const MATCH_IMAGE_CHANGED = "MATCH_IMAGE_CHANGED";
export const MATCH_TITLE_CHANGED = "MATCH_TITLE_CHANGED";
export const MATCH_DESCRIPTION_CHANGED = "MATCH_DESCRIPTION_CHANGED";
export const MATCH_POINTS_CHANGED = "MATCH_POINTS_CHANGED";
export const MATCH_CITY_CHANGED = "MATCH_CITY_CHANGED";
export const MATCH_PHONE_CHANGED = "MATCH_PHONE_CHANGED";
export const MATCH_PICKUP_CHANGED = "MATCH_PICKUP_CHANGED";
export const MATCH_FRIEND_CHANGED = "MATCH_FRIEND_CHANGED";
export const MATCH_COMPLETE_TIME_CHANGED = "MATCH_COMPLETE_TIME_CHANGED";
export const MATCH_STATUS_CHANGED = "MATCH_STATUS_CHANGED";
export const MATCH_RATING_CHANGED = "MATCH_RATING_CHANGED";

export const ROUND_ADD = "ROUND_ADD";
export const ROUND_REMOVE = "ROUND_REMOVE";

export const MATCH_DETAIL = "MATCH_DETAIL";
export const MATCH_DETAIL_SUCCESS = "MATCH_DETAIL_SUCCESS";
export const MATCH_DETAIL_FAIL = "MATCH_DETAIL_FAIL";

export const MATCH_DETAIL_EMPTY = "MATCH_DETAIL_EMPTY";
export const MATCH_SAVE = "MATCH_SAVE";
export const MATCH_SAVE_SUCCESS = "MATCH_SAVE_SUCCESS";
export const MATCH_SAVE_FAIL = "MATCH_SAVE_FAIL";

export const MATCH_UPDATE = "MATCH_UPDATE";
export const MATCH_UPDATE_SUCCESS = "MATCH_UPDATE_SUCCESS";
export const MATCH_UPDATE_FAIL = "MATCH_UPDATE_FAIL";

export const MATCH_LIST_FETCH = "MATCH_LIST_FETCH";
export const MATCH_LIST_FETCH_SUCCESS = "MATCH_LIST_FETCH_SUCCESS";
export const MATCH_LIST_FETCH_FAIL = "MATCH_LIST_FETCH_FAIL";

export const IN_PROGRESS_LOAD_FETCH = "IN_PROGRESS_LOAD_FETCH";
export const IN_PROGRESS_LOAD_FETCH_SUCCESS = "IN_PROGRESS_LOAD_FETCH_SUCCESS";
export const IN_PROGRESS_LOAD_FETCH_FAIL = "IN_PROGRESS_LOAD_FETCH_FAIL";

export const TRACKING_LOCATION_SAVE = "TRACKING_LOCATION_SAVE";
export const TRACKING_LOCATION_SAVE_SUCCESS = "TRACKING_LOCATION_SAVE_SUCCESS";
export const TRACKING_LOCATION_SAVE_FAIL = "TRACKING_LOCATION_SAVE_FAIL";

export const SHIPMENT_LIST_FETCH = "SHIPMENT_LIST_FETCH";
export const SHIPMENT_LIST_FETCH_SUCCESS = "SHIPMENT_LIST_FETCH_SUCCESS";
export const SHIPMENT_LIST_FETCH_FAIL = "SHIPMENT_LIST_FETCH_FAIL";

export const WINNER_IMAGES_ADD = "WINNER_IMAGES_ADD";
export const WINNER_IMAGES_REMOVE = "WINNER_IMAGES_REMOVE";

// General Constants
export const MATCH_STATUS_PENDING = 1;
export const MATCH_STATUS_INPROGRESS = 2;
export const MATCH_STATUS_COMPLETED = 3;
export const MATCH_STATUS_REVIEW_PENDING = 4;
export const MATCH_STATUS_DISPUTED = 5;
export const MATCH_STATUS_END = 6;
export const MATCH_STATUS_CANCELLED_BOFORE_START = 7;
export const MATCH_STATUS_CANCELLED_AFTER_START = 8;
export const MATCH_STATUS_EXPIRED = 10;

// Profile
export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAIL = "PROFILE_FETCH_FAIL";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_AVATAR_UPDATE = "PROFILE_AVATAR_UPDATE";
export const PROFILE_AVATAR_UPDATE_SUCCESS = "PROFILE_AVATAR_UPDATE_SUCCESS";
export const PROFILE_AVATAR_UPDATE_FAIL = "PROFILE_AVATAR_UPDATE_FAIL";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";

export const STORAGE_KEY = "NUCA-MMA:key";

export const API_CLIENT_ERROR = 'CLIENT_ERROR';
export const API_SERVER_ERROR = 'SERVER_ERROR';
export const API_TIMEOUT_ERROR = 'TIMEOUT_ERROR';
export const API_CONNECTION_ERROR = 'CONNECTION_ERROR';
export const API_NETWORK_ERROR = 'NETWORK_ERROR';
export const API_CANCEL_ERROR = 'CANCEL_ERROR';

export const TYPE_GENERAL = 1;
export const TYPE_DRIVE = 2;
export const TYPE_PICK = 3;
